# deeptrack.elementwise

<a href="https://colab.research.google.com/github/DeepTrackAI/DeepTrack2/blob/develop/tutorials/3-advanced-topics/DTAT389_elementwise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# !pip install deeptrack  # Uncomment if running on Colab/Kaggle.

This advanced tutorial introduces the elementwise module.

## 1. What is elementwise?

The elementwise module introduces utility functions which lets the user apply Numpy functions to `Feature` objects elementwise.
Some functions included in elementwise are:

- Trigonometric
- Hyperbolic
- Rounding 
- Exponents and Logarithms
- Complex 

## 2. Initialize a `Feature`

We create a feature that subtracts values from an image.

In [ ]:
import numpy as np
from deeptrack.features import Feature


class Subtract(Feature):
    def get(self, image, value, **kwargs):
        return image - value

subtract_10 = Subtract(value=10)

input_image = np.array([1, 2, 3])
output_image = subtract_10(input_image)
print(output_image)

[-9 -8 -7]


## 3. Compute the Absolute value of the feature (In sequence)


In [ ]:
from deeptrack.elementwise import Abs


# Sequentially take the absolute value after subtraction.
pipeline = Abs(subtract_10)
output_image = pipeline(input_image)
print(output_image)

# Or equivalently:
pipeline = subtract_10 >> Abs()
output_image = pipeline(input_image)
print(output_image)



[9 8 7]
[9 8 7]
